version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3-venv
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install --upgrade pip wheel
      - pip3 install -r requirements.txt
      - mkdir test-reports
  build:
    commands:
      - pytest
        --html=test-reports/report.html
        --self-contained-html
        -s
        -v
        --cov=.
        --cov-report=html:test-reports/coverage
        --junitxml=test-reports/junit.xml
        --log-file=test-reports/logs.txt
        .
      - python3 setup.py bdist_wheel
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  wheel:
    files:
      - "*.whl"
    base-directory: 'dist'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml
